# Generated by Django 5.0.6 on 2024-06-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=200)),
                ('species_genom', models.CharField(max_length=500)),
                ('can_move', models.BooleanField(default=False)),
                ('can_defend', models.BooleanField(default=False)),
            ],
        ),
    ]
