# Generated by Django 5.0.6 on 2024-06-05 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('also', '0002_rename_species_genom_species_species_genome'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 11, 43, 2, 559284), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='species',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='species_description',
            field=models.CharField(default='description', max_length=500),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_genome',
            field=models.CharField(default='genome', max_length=500),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
