# Generated by Django 5.0.6 on 2024-06-07 10:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('also', '0005_alter_species_pub_date_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_species', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='species',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 12, 19, 9, 964617), verbose_name='date published'),
        ),
    ]
