# Generated by Django 5.0.6 on 2024-06-07 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('also', '0006_species_user_alter_species_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 12, 30, 23, 846729), verbose_name='date published'),
        ),
    ]
